baseurl = "https://pbx-group-security.com"

title = "Photobox Group Security"
theme = "./layouts"
themesDir = "./"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = 10
#disqusShortname = "pbx-group-security-com"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-111337742-1"

ignoreFiles = [ "^\\.#", "^\\#", "^\\.*.swp" ]

# To generate json pages, we need this here
# And on each page, you add the list of outputs
[outputs]
  home = ["HTML", "stats"]
  page = ["HTML", "JSON"]

# New output format to be served at {baseURL}/stats.html 
# Display quick website content stats overview
[outputFormats.stats]
mediaType = "text/html"
baseName = "stats"

[social]
twitter = "pbg_security"
twitter_domain = "pbg_security"
facebook = ""

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "About Us"
    url  = "/about-us/"
    weight = 2

[[menu.main]]
    name = "Roles"
    identifier = "role"
    url  = "/roles/"
    weight = 3

[[menu.main]]
    name = "Challenges"
    identifier = "challenges"
    url  = "/challenges/"
    weight = 5

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 6


[[menu.main]]
    name = "Working Sessions"
    url  = "/working-sessions/"
    weight = 7

#[[menu.main]]
#    name = "Dev"
#    url  = "/page/dev/"
#    weight = 5

#[[menu.main]]
#    name = "Contact"
#    url  = "/page/contact/"
#    weight = 8

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/photobox"
    pre = "<i class='fa fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/PBG_Security"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:project-cx@photobox.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Photobox Group Security"
    defaultKeywords = ["photobox", "security", "blog"]
    defaultDescription = "Welcome to Photobox Group Security's hub"
    ghRepo = "https://github.com/photobox/pbx-group-security/"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    #?Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    #?Enable the contact form by entering your Formspree.io email
    email = "project-cx@photobox.com"

    about_us = "<p>Photobox Group is Europe's leading digital consumer service for personalised products and gifts and parent of the Photobox, Moonpig, Hofmann and posterXXL brands.<p>"
    copyright = '&copy; 2018, Photobox Group Security. This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.'

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "/img/pbx-gs/pbx-gs-logo.png"
    address = """<p><strong>Photobox Group Security</strong>
        <br>Unit 7, Metal Box Factory
        <br>30 Great Guildford Street
        <br>London
        <br>SE1 0HS
        <br>England
      </p>
      """
    latitude = "51.50462899999999"
    longitude = "-0.09706600000004073"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "Here’s what the team has to say about working at Photobox"

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Our blog"
    subtitle = "Read our latest blog posts here"
